import { useRef, useState } from 'react'
import Reveal from '../common/Reveal'
import { exportNodeAsPng } from '../../utils/exportPng'

export default function SummarySection({ data }) {
  const cardRef = useRef(null)
  const [exporting, setExporting] = useState(false)

  async function handleExport() {
    if (!cardRef.current) return
    setExporting(true)
    try {
      await exportNodeAsPng(cardRef.current, `${data.handle}-cp-summary.png`)
    } catch {
      // Export can fail on some browsers/extensions blocking canvas reads —
      // fail quietly rather than crashing the page over a non-critical action.
    } finally {
      setExporting(false)
    }
  }

  return (
    <section className="min-h-screen flex flex-col justify-center items-center px-6">
      <Reveal>
        <p className="text-xs uppercase tracking-wide text-neutral-500 mb-2 text-center">
          chapter 4
        </p>
        <h2 className="text-2xl font-medium mb-8 text-center">the summary card</h2>

        <div
          ref={cardRef}
          className="bg-neutral-900 rounded-2xl p-6 border border-neutral-800 w-full max-w-sm"
        >
          <p className="text-neutral-500 text-xs mb-1">codeforces</p>
          <p className="text-xl font-semibold mb-4">{data.handle}</p>

          <div className="grid grid-cols-2 gap-3 mb-4">
            <div>
              <p className="text-neutral-500 text-xs">rating</p>
              <p className="text-lg font-medium">{data.currentRating}</p>
            </div>
            <div>
              <p className="text-neutral-500 text-xs">rank</p>
              <p className="text-lg font-medium">{data.rank}</p>
            </div>
            <div>
              <p className="text-neutral-500 text-xs">solved</p>
              <p className="text-lg font-medium">{data.solved.totalSolved}</p>
            </div>
            <div>
              <p className="text-neutral-500 text-xs">contests</p>
              <p className="text-lg font-medium">{data.contestsCount}</p>
            </div>
          </div>

          <p className="text-neutral-600 text-[10px]">generated by codestars dashboard</p>
        </div>

        <button
          onClick={handleExport}
          disabled={exporting}
          className="mt-6 bg-emerald-500 text-emerald-950 text-sm font-medium px-5 py-2.5 rounded-lg hover:bg-emerald-400 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {exporting ? 'exporting...' : 'export as png'}
        </button>
      </Reveal>
    </section>
  )
}
